name: 'Geojson Lint'
description: 'Run @mapbox/geojsonhint on geojson files in pull requests'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
